# Generated by Django 3.0.4 on 2020-03-12 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='id',
        ),
        migrations.AlterField(
            model_name='member',
            name='myid',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
